steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x ./get_schema_list.sh
        ./get_schema_list.sh

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +r /workspace/new_schema_filepaths.env
        chmod +r /workspace/error_directories.env
        chmod +x ./send_pubsub_messages.sh
        ./send_pubsub_messages.sh

options:
  logging: CLOUD_LOGGING_ONLY