steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Target directory for the schemas
        SCHEMA_DIRECTORY=$SCHEMA_DIRECTORY
        BRANCH_NAME=$BRANCH_NAME

        # Initialise the lists
        NEW_SCHEMA_FILEPATHS=()
        ERROR_DIRECTORIES=()

        # Get the list of newly added files in the commit
        NEW_FILES=$(git diff --name-only --diff-filter=A HEAD~1 HEAD)

        # Filter the files to only include new schemas in the schema_directory
        NEW_SCHEMAS=$(echo "$NEW_FILES" | grep "^$SCHEMA_DIRECTORY/")

        # Iterate over each subdirectory in the schema_directory
        for SUBDIR in $(find $SCHEMA_DIRECTORY -mindepth 1 -maxdepth 1 -type d); do
          # Get the list of new schemas in the subdirectory
          NEW_SCHEMAS_IN_SUBDIR=$(echo "$NEW_SCHEMAS" | grep "^$SUBDIR/")

          # Count the number of new schemas in the subdirectory
          NUM_NEW_SCHEMAS=$(echo "$NEW_SCHEMAS_IN_SUBDIR" | wc -l)

          if [ "$NUM_NEW_SCHEMAS" -eq 1 ]; then
            # If there is exactly one new schema, add it to the NEW_SCHEMA_FILEPATHS list
            NEW_SCHEMA_FILEPATHS+=("$NEW_SCHEMAS_IN_SUBDIR")
          elif [ "$NUM_NEW_SCHEMAS" -gt 1 ]; then
            # If there is more than one new schema, add the subdirectory to the ERROR_DIRECTORIES list
            ERROR_DIRECTORIES+=("$SUBDIR")
          fi
        done

        # Write the lists to environment variable files
        echo "NEW_SCHEMA_FILEPATHS=${NEW_SCHEMA_FILEPATHS[@]}" > /workspace/new_schema_filepaths.env
        echo "ERROR_DIRECTORIES=${ERROR_DIRECTORIES[@]}" > /workspace/error_directories.env

  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Load the environment variables
        source /workspace/new_schema_filepaths.env
        source /workspace/error_directories.env
        NEW_SCHEMA_PUBSUB_TOPIC=$NEW_SCHEMA_PUBSUB_TOPIC
        SCHEMA_FAILURE_PUBSUB_TOPIC=$SCHEMA_FAILURE_PUBSUB_TOPIC

        # Print the lists
        echo "NEW_SCHEMA_FILEPATHS: ${NEW_SCHEMA_FILEPATHS[@]}"
        echo "ERROR_DIRECTORIES: ${ERROR_DIRECTORIES[@]}"

        # loop through new schemas
        for NEW_SCHEMA_FILEPATH in "${NEW_SCHEMA_FILEPATHS[@]}"; do
          echo "Processing new schema: $NEW_SCHEMA_FILEPATH"
          # send a pubsub message with the schema file path
          gcloud pubsub topics publish $NEW_SCHEMA_PUBSUB_TOPIC --message $NEW_SCHEMA_FILEPATH
        done

        # loop through error directories
        for ERROR_DIRECTORY in "${ERROR_DIRECTORIES[@]}"; do
          echo "Error: More than one new schema in directory: $ERROR_DIRECTORY"
          # send a pubsub message with the error directory
          gcloud pubsub topics publish $SCHEMA_FAILURE_PUBSUB_TOPIC --message $ERROR_DIRECTORY
        done

options:
  logging: CLOUD_LOGGING_ONLY