steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Get last commit for comparison"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=schema-publish-commit-hash > /workspace/last_commit_hash.env

  - name: "gcr.io/cloud-builders/git"
    id: "Get schema list"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod +x ./get_schema_list.sh
        ./get_schema_list.sh

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Send PubSub messages"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod +x ./send_pubsub_messages.sh
        ./send_pubsub_messages.sh

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Store commit hash in Secret Manager"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions add schema-publish-commit-hash --data-file=/workspace/latest_commit_hash.env

options:
  logging: CLOUD_LOGGING_ONLY
