name: Scan and Call Python Script

on:
  push:
    branches:
      - main

jobs:
  scan-and-call-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up GCP credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Scan and call Python script
      run: |

        
        if [ -z "${{ github.event.before }}" ]; then
          # handle case where github.event.before is not available e.g. first commit
          CHANGED_FILES=$(ls schemas/)
        else
          # get list of changed files using git diff
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- schemas/)
        fi

        if [ -n "$CHANGED_FILES" ]; then
          for FILE in $CHANGED_FILES; do
            python publish.py "$(cat $FILE)"
          done
        else
          echo "No changes in /schemas directory."
        fi
