name: Scan and Call Python Script

on:
  push:
    branches:
      - main
    

jobs:
  scan-and-call-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up GCP credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Scan and call Python script
      run: |
        if [ -z "${{ github.event.before}}"] || [ -z "${{ github.sha}}"]; then
          echo "Error: 'github.event.before' or 'github.sha' is not set"
          exit 1
        fi
        
        if [ ! -d "schemas/" ]; then
          echo "Error: schemas/ directory does not exist."
          exit 1
        fi

        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- schemas/) || {
          echo "Error: git diff command failed."
          exit 1
        }
        done