name: Scan and Call Python Script

on:
  push:
    branches:
      - main
    

jobs:
  scan-and-call-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch the full history

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up GCP credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Scan and call Python script
      run: |
        # Get the list of changed files
        if [ -z "${{ github.event.before }}" ]; then
          # Handle case where github.event.before is not available (e.g., first commit)
          CHANGED_FILES=$(ls schemas/)
        else
          # Get list of changed files using git diff
          CHANGED_FILES=$(git diff --name-only --ignore-blank-lines ignore-all-space ${{ github.event.before }} ${{ github.sha }} -- schemas/)
        fi

        # Process each changed file
        if [ -n "$CHANGED_FILES" ]; then
          for FILE in $CHANGED_FILES; do
            # Call Python script with the filename
            echo $FILE
            python publish.py "$FILE"
          done
        else
          echo "No changes in /schemas directory."
        fi
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}