name: Scan and Call Python Script

on:
  push:
    branches:
      - main
    paths:
      - 'schemas/**'

jobs:
  scan-and-call-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up GCP credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: List files in /schemas directory
      id: list-files
      run: |
          cd schemas
          find . -type f > ../file_list.txt
  
    - name: Compare files with previous state
      id: compare-files
      run: |
        CHANGED_FILES=""
        while IFS= read -r FILE; do
          PREVIOUS_FILE=$(git show HEAD^:"schemas/$FILE" 2>/dev/null)
          CURRENT_FILE=$(cat "schemas/$FILE")
          if ! git diff --ignore-all-space --exit-code <(echo "$PREVIOUS_FILE") <(echo "$CURRENT_FILE") &> /dev/null; then
            CHANGED_FILES="$CHANGED_FILES $FILE"
          fi
        done < file_list.txt
        echo "::set-output name=changed_files::$CHANGED_FILES"

    - name: Run Python script for changed files
      if: steps.compare-files.outputs.changed_files != ''
      run: |
        for FILE in ${{ steps.compare-files.outputs.changed_files }}; do
          python publish.py "schemas/$FILE"
        done